// khanza-nuxt/pages/admin/garage.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';

definePageMeta({
  layout: 'admin',
  middleware: 'admin'
});
useSeoMeta({ title: 'Kelola Galeri - Admin' });

interface GarageItem {
  id: number;
  car_model: string;
  year: number;
  price: number;
  description: string;
  images: string;
  status: 'available' | 'sold';
}

const items = ref<GarageItem[]>([]);
const loading = ref(true);
const isModalOpen = ref(false);
const editingItem = ref<GarageItem | null>(null);
const uploading = ref(false);
const fileInput = ref<HTMLInputElement | null>(null);

const formData = ref({
  car_model: '',
  year: new Date().getFullYear(),
  price: 0,
  description: '',
  images: '',
  status: 'available' as 'available' | 'sold'
});

const fetchItems = async () => {
  loading.value = true;
  try {
    const data: any = await $fetch('/api/garage');
    items.value = data;
  } catch (err) {
    console.error(err);
  } finally {
    loading.value = false;
  }
};

onMounted(() => {
  fetchItems();
});

const handleOpenModal = (item?: GarageItem) => {
  if (item) {
    editingItem.value = item;
    formData.value = { ...item };
  } else {
    editingItem.value = null;
    formData.value = {
      car_model: '',
      year: new Date().getFullYear(),
      price: 0,
      description: '',
      images: '',
      status: 'available'
    };
  }
  isModalOpen.value = true;
};

const handleCloseModal = () => {
  isModalOpen.value = false;
  editingItem.value = null;
};

const handleImageUpload = async (e: Event) => {
  const target = e.target as HTMLInputElement;
  const file = target.files?.[0];
  if (!file) return;

  uploading.value = true;
  const uploadData = new FormData();
  uploadData.append('image', file);

  try {
    const token = localStorage.getItem('adminToken');
    const data: any = await $fetch('/api/admin/upload', {
      method: 'POST',
      headers: { Authorization: `Bearer ${token}` },
      body: uploadData
    });
    formData.value.images = data.url;
  } catch (err: any) {
    alert(err.response?._data?.error || 'Gagal mengunggah gambar.');
  } finally {
    uploading.value = false;
    if (fileInput.value) fileInput.value.value = '';
  }
};

const handleSubmit = async () => {
  const token = localStorage.getItem('adminToken');
  const url = editingItem.value ? `/api/admin/garage/${editingItem.value.id}` : '/api/admin/garage';
  const method = editingItem.value ? 'PUT' : 'POST';

  try {
    await $fetch(url, {
      method,
      headers: { Authorization: `Bearer ${token}` },
      body: formData.value
    });
    fetchItems();
    handleCloseModal();
  } catch (err) {
    console.error(err);
    alert('Terjadi kesalahan saat menyimpan kendaraan');
  }
};

const handleDelete = async (id: number) => {
  if (!confirm('Yakin ingin menghapus kendaraan ini?')) return;
  const token = localStorage.getItem('adminToken');
  try {
    await $fetch(`/api/admin/garage/${id}`, {
      method: 'DELETE',
      headers: { Authorization: `Bearer ${token}` }
    });
    fetchItems();
  } catch (err) {
    console.error(err);
    alert('Gagal menghapus kendaraan');
  }
};

const formatRupiah = (value: number) => {
  return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }).format(value);
};

const statusLabels: Record<string, string> = {
  available: 'Tersedia',
  sold: 'Terjual'
};
</script>

<template>
  <div class="space-y-6">
    <div class="flex justify-between items-center">
      <h1 class="text-3xl font-bold">Kelola Galeri</h1>
      <button
        @click="handleOpenModal()"
        class="flex items-center gap-2 px-4 py-2 bg-red-600 hover:bg-red-700 text-white rounded-none transition-colors"
      >
        <Icon name="cil:plus" :size="20" /> Tambah Kendaraan
      </button>
    </div>

    <div v-if="loading" class="flex justify-center py-20">
      <Icon name="cil:reload" class="animate-spin text-red-500" :size="48" />
    </div>

    <div v-else class="bg-white/5 border border-white/10 rounded-none overflow-hidden">
      <table class="w-full text-left border-collapse">
        <thead>
          <tr class="bg-white/5 border-b border-white/10">
            <th class="p-4 font-medium text-gray-400">Gambar</th>
            <th class="p-4 font-medium text-gray-400">Model</th>
            <th class="p-4 font-medium text-gray-400">Tahun</th>
            <th class="p-4 font-medium text-gray-400">Harga</th>
            <th class="p-4 font-medium text-gray-400">Status</th>
            <th class="p-4 font-medium text-gray-400 text-right">Aksi</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="item in items" :key="item.id" class="border-b border-white/5 hover:bg-white/5 transition-colors">
            <td class="p-4">
              <img v-if="item.images" :src="item.images" :alt="item.car_model" class="w-16 h-16 object-cover rounded-none" referrerpolicy="no-referrer" />
              <div v-else class="w-16 h-16 bg-white/10 rounded-none flex items-center justify-center text-gray-500">
                <Icon name="cil:image" Icon :size="24" />
              </div>
            </td>
            <td class="p-4 font-medium">{{ item.car_model }}</td>
            <td class="p-4 text-gray-400">{{ item.year }}</td>
            <td class="p-4">{{ formatRupiah(item.price) }}</td>
            <td class="p-4">
              <span class="px-3 py-1 rounded-none text-xs font-bold uppercase tracking-wider"
                :class="item.status === 'available' ? 'bg-green-500/20 text-green-400 border border-green-500/30' : 'bg-red-500/20 text-red-400 border border-red-500/30'"
              >
                {{ statusLabels[item.status] || item.status }}
              </span>
            </td>
            <td class="p-4 flex justify-end gap-2 items-center h-full">
              <button
                @click="handleOpenModal(item)"
                class="p-2 text-blue-400 hover:bg-blue-400/10 rounded-none transition-colors"
              >
                <Icon name="cil:pencil" :size="18" />
              </button>
              <button
                @click="handleDelete(item.id)"
                class="p-2 text-red-400 hover:bg-red-400/10 rounded-none transition-colors"
              >
                <Icon name="cil:trash" :size="18" />
              </button>
            </td>
          </tr>
          <tr v-if="items.length === 0">
            <td colspan="6" class="p-8 text-center text-gray-500">Belum ada kendaraan.</td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Modal Form -->
    <div v-if="isModalOpen" class="fixed inset-0 bg-black/80 backdrop-blur-sm flex items-center justify-center z-[100] p-4">
      <div
        v-motion
        :initial="{ opacity: 0, scale: 0.95 }"
        :enter="{ opacity: 1, scale: 1 }"
        class="bg-[#111] border border-white/10 p-6 rounded-none w-full max-w-md relative max-h-[90vh] overflow-y-auto"
      >
        <button
          @click="handleCloseModal"
          class="absolute top-4 right-4 text-gray-400 hover:text-white transition-colors"
        >
          <Icon name="cil:x" :size="24" />
        </button>
        <h2 class="text-2xl font-bold mb-6">{{ editingItem ? 'Edit Kendaraan' : 'Tambah Kendaraan' }}</h2>
        <form @submit.prevent="handleSubmit" class="space-y-4">
          <div>
            <label class="block text-sm font-medium text-gray-400 mb-1">Model Kendaraan</label>
            <input
              type="text" required
              v-model="formData.car_model"
              class="w-full px-4 py-2 bg-black/50 border border-white/10 rounded-none text-white focus:border-red-500 focus:ring-1 focus:ring-red-500 outline-none"
            />
          </div>
          <div class="grid grid-cols-2 gap-4">
            <div>
              <label class="block text-sm font-medium text-gray-400 mb-1">Tahun</label>
              <input
                type="number" required min="1900" :max="new Date().getFullYear() + 1"
                v-model="formData.year"
                class="w-full px-4 py-2 bg-black/50 border border-white/10 rounded-none text-white focus:border-red-500 focus:ring-1 focus:ring-red-500 outline-none"
              />
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-400 mb-1">Harga (Rp)</label>
              <input
                type="number" required min="0" step="1000"
                v-model="formData.price"
                class="w-full px-4 py-2 bg-black/50 border border-white/10 rounded-none text-white focus:border-red-500 focus:ring-1 focus:ring-red-500 outline-none"
              />
            </div>
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-400 mb-1">Status</label>
            <select
              v-model="formData.status"
              class="w-full px-4 py-2 bg-black/50 border border-white/10 rounded-none text-white focus:border-red-500 focus:ring-1 focus:ring-red-500 outline-none appearance-none"
            >
              <option value="available">Tersedia</option>
              <option value="sold">Terjual</option>
            </select>
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-400 mb-1">URL Gambar</label>
            <div class="flex gap-2">
              <input
                type="url" required
                v-model="formData.images"
                placeholder="https://contoh.com/gambar.jpg"
                class="flex-1 px-4 py-2 bg-black/50 border border-white/10 rounded-none text-white focus:border-red-500 focus:ring-1 focus:ring-red-500 outline-none"
              />
              <input
                type="file"
                accept="image/*"
                class="hidden"
                ref="fileInput"
                @change="handleImageUpload"
              />
              <button
                type="button"
                @click="fileInput?.click()"
                :disabled="uploading"
                class="px-4 py-2 bg-white/10 hover:bg-white/20 text-white rounded-none transition-colors disabled:opacity-50 flex items-center gap-2"
              >
                <Icon name="cil:reload" v-if="uploading" class="animate-spin" :size="18" />
                <Icon name="cil:cloud-upload" v-else :size="18" />
              </button>
            </div>
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-400 mb-1">Deskripsi</label>
            <textarea
              required rows="4"
              v-model="formData.description"
              class="w-full px-4 py-2 bg-black/50 border border-white/10 rounded-none text-white focus:border-red-500 focus:ring-1 focus:ring-red-500 outline-none resize-none"
            ></textarea>
          </div>
          <button
            type="submit"
            :disabled="uploading"
            class="w-full py-3 bg-red-600 hover:bg-red-700 text-white font-bold rounded-none transition-colors mt-4 disabled:opacity-50"
          >
            {{ editingItem ? 'Simpan Perubahan' : 'Tambah Kendaraan' }}
          </button>
        </form>
      </div>
    </div>
  </div>
</template>

// src/pages/Garage.tsx
import { motion } from 'motion/react';
import { Search, Loader2, Eye, X, ChevronLeft, ChevronRight } from 'lucide-react';
import { useState, useEffect } from 'react';
import type { Car } from '../types';
import Spinner from '../components/ui/Spinner';

const formatRupiah = (value: number | string) => {
  const num = typeof value === 'string' ? parseFloat(value) : value;
  if (isNaN(num)) return value;
  return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0, maximumFractionDigits: 0 }).format(num);
};

export default function Garage() {
  const [searchTerm, setSearchTerm] = useState('');
  const [inventory, setInventory] = useState<Car[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [selectedCar, setSelectedCar] = useState<Car | null>(null);
  const [viewMode, setViewMode] = useState<'grid' | 'list'>('grid');

  useEffect(() => {
    const fetchGarage = async () => {
      try {
        const res = await fetch('/api/garage');
        if (!res.ok) throw new Error('Gagal memuat inventaris');
        const data = await res.json();
        setInventory(data);
      } catch (err) {
        setError('Gagal memuat inventaris galeri.');
      } finally {
        setLoading(false);
      }
    };
    fetchGarage();
  }, []);

  const filteredInventory = inventory.filter(car =>
    car.status === 'available' && car.car_model.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="max-w-7xl mx-auto px-6 py-16 md:py-20">
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="mb-12"
      >
        <div className="flex items-center gap-2 mb-4">
          <div className="w-8 h-[2px] bg-red-500" />
          <span className="text-red-500 text-sm font-semibold tracking-wider uppercase">Koleksi Kami</span>
        </div>
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
          <div>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold mb-3 tracking-tight">
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-red-500 to-red-700">Galeri</span> Kami
            </h1>
            <p className="text-gray-500 max-w-xl text-lg">
              Jelajahi koleksi kendaraan premium kami yang telah dirawat dengan teliti dan siap untuk pemilik barunya.
            </p>
          </div>

          {/* Filter Bar */}
          <div className="flex items-center gap-3">
            <div className="relative">
              <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-500" size={18} />
              <input
                type="text"
                placeholder="Cari kendaraan..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full md:w-64 pl-11 pr-4 py-3 rounded-xl bg-white/[0.03] border border-white/[0.06] text-white placeholder-gray-600 text-sm focus:outline-none focus:border-red-500/40 transition-colors"
              />
            </div>
            <div className="flex rounded-xl border border-white/[0.06] overflow-hidden">
              <button
                onClick={() => setViewMode('grid')}
                className={`p-3 text-sm transition-colors ${viewMode === 'grid' ? 'bg-white/[0.06] text-white' : 'text-gray-600 hover:text-gray-400'}`}
                aria-label="Tampilan grid"
              >
                <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><rect width="7" height="7" /><rect x="9" width="7" height="7" /><rect y="9" width="7" height="7" /><rect x="9" y="9" width="7" height="7" /></svg>
              </button>
              <button
                onClick={() => setViewMode('list')}
                className={`p-3 text-sm transition-colors ${viewMode === 'list' ? 'bg-white/[0.06] text-white' : 'text-gray-600 hover:text-gray-400'}`}
                aria-label="Tampilan daftar"
              >
                <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><rect width="16" height="3" /><rect y="6.5" width="16" height="3" /><rect y="13" width="16" height="3" /></svg>
              </button>
            </div>
          </div>
        </div>
      </motion.div>

      {loading ? (
        <Spinner size="lg" className="py-20" />
      ) : error ? (
        <div className="text-center py-20 text-red-400 bg-red-500/5 rounded-2xl border border-red-500/10">
          <p className="text-lg">{error}</p>
        </div>
      ) : (
        <div className={viewMode === 'grid' ? 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6' : 'space-y-4'}>
          {filteredInventory.map((car, idx) => (
            <motion.div
              key={car.id}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-50px" }}
              transition={{ duration: 0.4, delay: idx * 0.05 }}
              className={`group rounded-2xl overflow-hidden bg-white/[0.02] border border-white/[0.06] hover:border-white/[0.1] transition-all duration-500 ${viewMode === 'list' ? 'flex flex-col md:flex-row' : ''
                }`}
            >
              <div className={`relative overflow-hidden ${viewMode === 'list' ? 'md:w-72 aspect-[4/3] md:aspect-auto' : 'aspect-[4/3]'}`}>
                <img
                  src={car.images}
                  alt={car.car_model}
                  referrerPolicy="no-referrer"
                  loading="lazy"
                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
                <div className="absolute top-3 right-3 px-2.5 py-1 rounded-lg bg-black/50 backdrop-blur-md text-white text-xs font-semibold border border-white/10">
                  {car.year}
                </div>
                <button
                  onClick={() => setSelectedCar(car)}
                  className="absolute bottom-3 right-3 p-2.5 rounded-xl bg-white/10 backdrop-blur-md text-white opacity-0 group-hover:opacity-100 transition-all duration-300 hover:bg-red-600 border border-white/10"
                  aria-label="Lihat cepat"
                >
                  <Eye size={16} />
                </button>
              </div>

              <div className="p-5 flex-1">
                <div className="flex justify-between items-start mb-3">
                  <div>
                    <h3 className="text-lg font-bold text-white group-hover:text-red-400 transition-colors">{car.car_model}</h3>
                    <p className="text-gray-600 text-sm">{car.description}</p>
                  </div>
                  <p className="text-lg font-bold text-white whitespace-nowrap ml-4">{formatRupiah(car.price)}</p>
                </div>

                <button
                  onClick={() => setSelectedCar(car)}
                  className="w-full py-3 rounded-xl bg-white/[0.04] border border-white/[0.06] hover:bg-red-600 hover:border-red-600 text-white font-medium text-sm transition-all duration-300"
                >
                  Lihat Detail
                </button>
              </div>
            </motion.div>
          ))}
        </div>
      )}

      {!loading && !error && filteredInventory.length === 0 && (
        <div className="text-center py-20">
          <div className="w-16 h-16 rounded-full bg-white/[0.04] flex items-center justify-center mx-auto mb-4">
            <Search size={24} className="text-gray-600" />
          </div>
          <p className="text-gray-500 text-lg mb-2">Kendaraan tidak ditemukan</p>
          <p className="text-gray-600 text-sm">Coba sesuaikan kata pencarian Anda</p>
        </div>
      )}

      {/* Detail Modal */}
      {selectedCar && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50 flex items-center justify-center p-4"
          onClick={() => setSelectedCar(null)}
        >
          <motion.div
            initial={{ scale: 0.95, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            className="bg-[#0a0a0a] border border-white/[0.08] rounded-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="relative aspect-video">
              <img src={selectedCar.images} alt={selectedCar.car_model} className="w-full h-full object-cover rounded-t-2xl" referrerPolicy="no-referrer" />
              <button
                onClick={() => setSelectedCar(null)}
                className="absolute top-4 right-4 p-2 rounded-xl bg-black/50 backdrop-blur-md text-white hover:bg-red-600 transition-colors border border-white/10"
                aria-label="Tutup"
              >
                <X size={18} />
              </button>
              <div className="absolute bottom-4 left-4 px-3 py-1.5 rounded-lg bg-black/50 backdrop-blur-md text-white text-sm font-bold border border-white/10">
                {selectedCar.year}
              </div>
            </div>

            <div className="p-6 md:p-8">
              <div className="flex justify-between items-start mb-4">
                <h2 className="text-2xl font-bold text-white">{selectedCar.car_model}</h2>
                <span className="text-2xl font-bold text-red-500">{formatRupiah(selectedCar.price)}</span>
              </div>
              <p className="text-gray-400 leading-relaxed mb-6">{selectedCar.description}</p>

              <div className="grid grid-cols-3 gap-3 mb-6">
                {[
                  { label: 'Tahun', value: selectedCar.year },
                  { label: 'Status', value: 'Tersedia' },
                  { label: 'Kondisi', value: 'Sangat Baik' },
                ].map((spec) => (
                  <div key={spec.label} className="p-3 rounded-xl bg-white/[0.03] border border-white/[0.06] text-center">
                    <p className="text-gray-500 text-xs mb-1">{spec.label}</p>
                    <p className="text-white font-semibold text-sm">{spec.value}</p>
                  </div>
                ))}
              </div>

              <button className="w-full py-3.5 rounded-xl bg-gradient-to-r from-red-600 to-red-700 text-white font-semibold hover:shadow-[0_0_20px_rgba(220,38,38,0.3)] transition-all">
                Tanyakan Kendaraan Ini
              </button>
            </div>
          </motion.div>
        </motion.div>
      )}
    </div>
  );
}
